//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public string TenVietTat { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public string SoDKKD { get; set; }
        public string NguoiDaiDien { get; set; }
        public string ChucVu { get; set; }
        public string SoDienThoaiNDD { get; set; }
        public string SoTaiKhoan { get; set; }
        public string TenNganHang { get; set; }
        public string ChuTaiKhoan { get; set; }
        public Nullable<bool> isDoanhNghiep { get; set; }
    }
}
