//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThucPham.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebThucPhamEntities : DbContext
    {
        public WebThucPhamEntities()
            : base("name=WebThucPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<NhomChucNang> NhomChucNangs { get; set; }
        public virtual DbSet<PhanQuyenChucNang> PhanQuyenChucNangs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual ObjectResult<sp_DanhSachSanPham_Result> sp_DanhSachSanPham(Nullable<int> namsx, Nullable<double> dongiatu, Nullable<double> dongiaden, string tensp)
        {
            var namsxParameter = namsx.HasValue ?
                new ObjectParameter("namsx", namsx) :
                new ObjectParameter("namsx", typeof(int));
    
            var dongiatuParameter = dongiatu.HasValue ?
                new ObjectParameter("dongiatu", dongiatu) :
                new ObjectParameter("dongiatu", typeof(double));
    
            var dongiadenParameter = dongiaden.HasValue ?
                new ObjectParameter("dongiaden", dongiaden) :
                new ObjectParameter("dongiaden", typeof(double));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSanPham_Result>("sp_DanhSachSanPham", namsxParameter, dongiatuParameter, dongiadenParameter, tenspParameter);
        }
    
        public virtual ObjectResult<spDanhSachDonHang_Result> spDanhSachDonHang(Nullable<System.DateTime> ngay, Nullable<int> idKhachHang, string thongTin)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            var thongTinParameter = thongTin != null ?
                new ObjectParameter("ThongTin", thongTin) :
                new ObjectParameter("ThongTin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDanhSachDonHang_Result>("spDanhSachDonHang", ngayParameter, idKhachHangParameter, thongTinParameter);
        }
    
        public virtual ObjectResult<rp_SanPhamTheoNam_Result> rp_SanPhamTheoNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rp_SanPhamTheoNam_Result>("rp_SanPhamTheoNam");
        }
    
        public virtual ObjectResult<rp_SanPhamSanXuatTheoNam_Result> rp_SanPhamSanXuatTheoNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rp_SanPhamSanXuatTheoNam_Result>("rp_SanPhamSanXuatTheoNam");
        }
    }
}
