//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenChucNang
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public Nullable<int> idChucNang { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
