//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public string MauSac { get; set; }
        public string PhanLoai { get; set; }
        public Nullable<bool> HetHang { get; set; }
        public string EmailNCC { get; set; }
        public string SoDienThoaiNCC { get; set; }
        public string HinhAnh { get; set; }
    }
}
